services:
  - type: web
    name: eduvote
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    startCommand: /usr/bin/supervisord -c /etc/supervisord.conf
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://eduvote-ws7e.onrender.com
      - key: BROADCAST_DRIVER
        value: reverb
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: sqlite
      - key: APP_KEY
        generateValue: true
      - key: REVERB_APP_ID
        value: 483119
      - key: REVERB_APP_KEY
        value: ol5jsmuo4ji7bwfbxqak
      - key: REVERB_APP_SECRET
        value: kf529uhfpgqgly8ftzzv
      - key: REVERB_HOST
        value: 0.0.0.0
      - key: REVERB_PORT
        value: 6001
      - key: REVERB_SCHEME
        value: http
      - key: VITE_REVERB_APP_KEY
        value: ol5jsmuo4ji7bwfbxqak
      - key: VITE_REVERB_HOST
        value: eduvote-ws7e.onrender.com
      - key: VITE_REVERB_PORT
        value: 443
      - key: VITE_REVERB_SCHEME
        value: wss
